# config.toml de Velocity
bind = "0.0.0.0:25565"  # Cambiado a 25565 para alinearse con lo que Koyeb usa
motd = "Proxy para EaglerCraft"
show-max-players = 20
show-ping-requests = false
player-info-forwarding-mode = "legacy"

[servers]
try = ["paper"]
[servers.paper]
address = "91.197.5.213:26666"  # Servidor Paper sigue en 26666
motd = "Tu Servidor Paper 1.21.x"
hidden = false
max-players = 20

online-mode = false
authentication-type = "OFFLINE"
compression-threshold = 256
compression-level = -1
connection-timeout = 30000
read-timeout = 30
kick-existing-players = false
prevent-client-proxy-connections = false
log-player-ip-addresses = true
balance-teams = false

[forced-default-server]
enabled = true
server = "paper"

[query]
enabled = false
port = 25565  # Cambiado a 25565
