bind = "0.0.0.0:25565"
motd = "Proxy para EaglerCraft"
show-max-players = 20
show-ping-requests = false
player-info-forwarding-mode = "legacy"
[servers]
try = ["paper"]
[servers.paper]
address = "91.197.5.213:26666"
motd = "Tu Servidor Paper 1.21.x"
hidden = false
max-players = 20
online-mode = false
authentication-type = "OFFLINE"
