servers:
  paper:
    motd: '&b&lTu Servidor Paper 1.21.8'
    address: 91.197.5.213:26666  # Reemplaza con tu dominio de MineStrator
    restricted: false
    hidden: false
    max_players: 20
listeners:
  - query_port: 26666
    motd: '&1Proxy para EaglerCraft'
    priorities:
      - paper
    bind_local_address: true
    host: 0.0.0.0:26666
    max_players: 20
    tab_size: 60
    force_default_server: true
    ping_passthrough: false
    short_ping: false
    timeout: 30000
    connection_throttle: -1
tab_list: GLOBAL_PING
player_shuffle: 0
ip_forward: true
online_mode: false
